# Licensed Materials - Property of IBM
# IBM Sterling Order Management (5725-D10), IBM Order Management (5737-D18)
# (C) Copyright IBM Corp. 2018 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ibm-oms.fullname" . }}-config
  labels:
    app: {{ template "ibm-oms.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install

data:
{{ (tpl (.Files.Glob "config/*").AsConfig . ) | indent 2 }}
