# Licensed Materials - Property of IBM
# IBM Sterling Order Management (5725-D10), IBM Order Management (5737-D18)
# (C) Copyright IBM Corp. 2018 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ibm-oms.fullname" . }}
  labels:
    app: {{ template "ibm-oms.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install

type: Opaque
data:
  consoleadminpassword: {{ .Values.appserver.secrets.consoleadminpassword | b64enc | quote }}
  consolenonadminpassword: {{ .Values.appserver.secrets.consolenonadminpassword | b64enc | quote }}
  dbpassword: {{ .Values.dbserver.password | b64enc | quote }}
