apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        ns: dev
      - cluster: prod
        url: https://kubernetes.default.svc
        ns: prod
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/ponvg/g-gitops.git
        targetRevision: HEAD
        path: sterling/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{ns}}'